### ISSUE TITLE
Tweaking MEMU

### ISSUE THREAD

**Issue by AlterEg0z** [Jamminroot/MEMU3#3]
Hey, need some help tweaking this. It works sometimes, but after it kills the target the aimbot aims to the right. While im using the debug info i see that most of the time the green circle doesnt show up too, what can i do to tweak this? Sometimes when im from an medium-close to the target shoots to the right side of the head too. Thx in advance!

**Comment by AlterEg0z** [comment]
I saw that the strenght which the aim goes to the right after it kills the target depends on strenght settings too.

**Comment by Jamminroot** [comment]
Probably color values vary, and would need adjustments. Make a bunch of screenshots with bars visible, get the average values of target colors, and use them in color presets.
For example:
![image](https://user-images.githubusercontent.com/6387654/112229330-389abc00-8c4c-11eb-853e-575af332116f.png)
Color in the middle has the color code:
`254, 92, 92`
Use in a color preset as follows:
92,92,254,<TOLERANCE>.
Adjust tolerance (or threshold, whatever you call it) to your liking - you can just use 4-5 colors and higher tolerance values (like 20+) - this way it's easier to get color tables done; However higher tolerance means higher error rate (when program detectes unnecessary colors).
I'd suggest using as much colors, as possible, with tolerance as low as ~12.
Tolerance (and delta which is used to compare against tolerance) in general means sum of all squared deltas.
Like this: (254,92,92) and target color in the preset being (250, 90, 92) with preset being (92, 90, 254, 30), for example. Evaluated delta is:
(254-250)^2 + (92-90)^2 + (92-92)^2 = 16+4 + 0 = 20
Target color tolerance is 30 - this means that color would match.
However, if the delta is lower (below 20), the color we are checking would not fit.
You'd have to experiment with this to get a grip of it.
